name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: flows
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: 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