name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Render PlantUML
        uses: plantuml/plantuml-action@v1
        with:
          files: '*.puml' # specify your PlantUML files
          output: 'diagrams' # specify the output directory for images

      - name: Commit and push diagrams
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add diagrams/*
          git commit -m "Render PlantUML diagrams"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
